name: Deploy

on:
    push:
        branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify     

      - name: Download Algolia CLI
        run: wget https://github.com/algolia/cli/releases/download/v${{vars.ALGOLIA_VERSION}}/algolia_${{vars.ALGOLIA_VERSION}}_linux_amd64.tar.gz

      - name: Install Algolia CLI
        run: tar -xf algolia_${{vars.ALGOLIA_VERSION}}_linux_amd64.tar.gz && cd algolia_${{vars.ALGOLIA_VERSION}}_linux_amd64 && sudo cp algolia /usr/local/bin
    
      # - name: Upload Index
        # run: algolia objects update blog -F ./public/index.json --wait --application-id "${{secrets.ALGOLIA_APPID}}" --admin-api-key "${{secrets.ALGOLIA_ADMINKEY}}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./public
          cname: blog.obimadu.pro